### ISSUE TITLE
sqlite3.ProgrammingError を解消する

### ISSUE THREAD

**Issue by naotsukamoto** [naotsukamoto/j-ikitai#16]
error の内容は以下
```
Exception closing connection <sqlite3.Connection object at 0x10e41dc60>
Traceback (most recent call last):
  File "/Users/tsukamotonao/.pyenv/versions/3.9.7/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 682, in _finalize_fairy
    fairy._reset(pool)
  File "/Users/tsukamotonao/.pyenv/versions/3.9.7/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 887, in _reset
    pool._dialect.do_rollback(self)
  File "/Users/tsukamotonao/.pyenv/versions/3.9.7/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 667, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 123145354211328 and this is thread id 140735732880256.
```

**Comment by naotsukamoto** [comment]
ユーザーごとに単一の thread でdb接続を使いまわしていたため、エラーが出ていた模様
create_engine 時に、`?check_same_thread=False"` で別 thread を立てるようにした
